# "/output/<SEED>/MLP_JNT_1409"
OUT_DIR: "/output/1409/MLP_JNT_1409"
RNG_SEED: 1409
ENV_NAME: "Robosuite-v0"

ROBOSUITE:
  TASK_TYPE: "SR" 
  TRAINING_MORPHOLOGIES: ["Panda"] # , "Jaco", "IIWA", "Kinova3", "UR5e", "Sawyer"
  ENV_NAMES: ["Lift"] # Door, PickPlace
  CONTROLLERS: ["JOINT_VELOCITY"] # OSC_POSE but we have to chanfe DECODER_OUT_DIM to 6

 
ENV:
  KEYS_TO_KEEP: ["proprioceptive", "obs_padding_mask", "act_padding_mask", "edges", "context"] 

MODEL:
  TYPE: "mlp" 
  DECODER_OUT_DIM: 1 # change to 6 for OSC_POSE
  OBS_TYPES: ["proprioceptive", "obs_padding_mask", "act_padding_mask", "edges", "context"]
  # stablize the learning process but not readable for rewards
  # could do it with rew=False 
  OBS_TO_NORM: []
  # ACTION_STD: 0.1 # for osc pose
  ACTION_STD_FIXED: False
  MLP:
     LAYER_NUM: 2

PPO:
  MAX_STATE_ACTION_PAIRS: 1e7 
  NUM_ENVS: 8  
  TIMESTEPS: 2560
  # dset(ts*num_env) >= batch_Stize
  BATCH_SIZE: 1024 # try with 5120
  KL_TARGET_COEF: 6 # 0.06
  ENTROPY_COEF: 0.001 
  BASE_LR: 0.001


DEVICE: "cuda:0" 

LOGGING:
  USE_WANDB: True 
  PROJECT: "Baselines"
  ENTITY: "alimidhat62-org"


