ENV_NAME: "Robosuite-v0"

ROBOSUITE:
  TASK_TYPE: "MR" 
  TRAINING_MORPHOLOGIES: ["Panda"] # , "Sawyer", "Jaco", "IIWA", "Kinova3", "UR5e"
  ENV_NAMES: ["Lift"] 
  CONTROLLERS: ["JOINT_VELOCITY"] #   OSC_POSE change decoder out dim to 6

 
ENV:
  KEYS_TO_KEEP: ["object-state", "proprioceptive", "obs_padding_mask", "act_padding_mask", "edges", "context", "SWAT_RE", "traversals"] 

MODEL:
  TYPE: "transformer" 
  OBS_TYPES: ["proprioceptive", "obs_padding_mask", "act_padding_mask", "edges", "context", "SWAT_RE", "traversals"]
  # stablize the learning process but not readable for rewards
  # log both normalized and unnormalized rew
  OBS_TO_NORM: []

 
  # for consistency when swap model type later.
  TRANSFORMER:
    NLAYERS: 1
    NHEAD: 1
    DIM_FEEDFORWARD: 256
    DECODER_OUT_DIM : 1
    KL_TARGET_COEF: 5 # 0.05
    DROPOUT: 0.0
    EXT_MIX: "late" 
    POS_EMBEDDING: "none" # swat_re/traversals are better?
    HYPERNET: True 
    FIX_ATTENTION: True 
    USE_SWAT_PE: True 
    USE_SWAT_RE: True
    HN_EMBED: True
    HN_DECODER: True 

# PPO training parameters
PPO:
  MAX_STATE_ACTION_PAIRS: 1e6 
  NUM_ENVS: 4
  TIMESTEPS: 2560 
  BATCH_SIZE: 1024 # dset(ts*num_env) >= batch_Stize


RNG_SEED: 1
DEVICE: "cuda:0"
LOG_PERIOD: 10
CHECKPOINT_PERIOD: 100

# Logging
LOGGING:
  USE_WANDB: False 
  PROJECT: "JNT_VS_OSC"
  ENTITY: "alimidhat62-org"


OUT_DIR: "" #./output/robosuite_transformer_lift/1409