ENV_NAME: "Robosuite-v0"
OUT_DIR: "out/1409/robosuite_single_task_transformer"
RNG_SEED: 1409

ROBOSUITE:
  ENV_NAME: "Lift"
  ROBOTS: ["Panda"]
  CONTROLLER: "JOINT_VELOCITY"

ENV:
  MOUDLES: []
  WRAPPERS: []
  #KEYS_TO_KEEP: ["proprioceptive"]
  #KEYS_TO_KEEP: ["object_state", "gripper_to_object", "eef_pos", "eef_quat", "gripper_qpos", "gripper_qvel"]
  

MODEL:
  TYPE: "transformer"
  MAX_LIMBS: 8
  MAX_JOINTS: 7
  
  TRANSFORMER:
    EXT_MIX: "late"




PPO:
  MAX_STATE_ACTION_PAIRS: 1e6
  TIMESTEPS: 1024
  EPOCHS: 8
  BATCH_SIZE: 512
  NUM_ENVS: 4

LOGGING:
  USE_WANDB: True
  PROJECT: "Single_Task_Transformer"
