ENV_NAME: "Robosuite-v0"
OUT_DIR: "out/1409/robosuite_Panda_Lift_mlp_1409"
RNG_SEED: 1409

ROBOSUITE:
  ENV_NAME: "Lift"
  ROBOTS: ["Panda"]
  CONTROLLER: "JOINT_VELOCITY"

ENV:
  MOUDLES: []
  WRAPPERS: []
  KEYS_TO_KEEP: ["proprioceptive"]
  #     "context",
  #     "edges",
  #     "obs_padding_mask",
  #     "act_padding_mask",
  #     "object-state", 
  #   ]

MODEL:
  TYPE: "mlp"
  MAX_LIMBS: 12
  MAX_JOINTS: 11
  # we define them as None to bypass any possible errors even if we are using mlp
  TRANSFORMER:
    EXT_MIX: None 



PPO:
  MAX_STATE_ACTION_PAIRS: 1e6
  NUM_ENVS: 8

LOGGING:
  USE_WANDB: True
  ENTITY: "alimidhat62-org"
  PROJECT: "Single_Panda_Lift"
